# Generated by Django 4.2.27 on 2025-12-12 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, help_text='Room/Office number', max_length=50)),
                ('office_location', models.CharField(blank=True, help_text='Specific office location', max_length=200)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Officer assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Assignment',
                'verbose_name_plural': 'Device Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the directorate (e.g., PS, AU, ASIA)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Physical location/building', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Directorate',
                'verbose_name_plural': 'Directorates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ICTEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop Computer'), ('tablet', 'Tablet'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('monitor', 'Monitor'), ('router', 'Router/Switch'), ('server', 'Server'), ('phone', 'Phone/Handset'), ('projector', 'Projector'), ('other', 'Other')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(help_text='Unique serial number', max_length=100, unique=True)),
                ('asset_tag', models.CharField(blank=True, help_text='Ministry asset tag', max_length=50, null=True, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_repair', 'Needs Repair'), ('decommissioned', 'Decommissioned')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('retired', 'Retired')], default='available', max_length=20)),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ICT Equipment',
                'verbose_name_plural': 'ICT Equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='equipment.deviceassignment')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='equipment.ictequipment')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Issue',
                'verbose_name_plural': 'Device Issues',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('relocated', 'Relocated'), ('returned', 'Returned'), ('repaired', 'Repaired'), ('replaced', 'Replaced'), ('condition_changed', 'Condition Changed'), ('status_changed', 'Status Changed')], max_length=30)),
                ('from_room', models.CharField(blank=True, max_length=50)),
                ('to_room', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='equipment.deviceassignment')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='equipment.ictequipment')),
                ('from_directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='equipment.directorate')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_actions', to=settings.AUTH_USER_MODEL)),
                ('to_directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='equipment.directorate')),
            ],
            options={
                'verbose_name': 'Device History',
                'verbose_name_plural': 'Device History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='directorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='equipment.directorate'),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='equipment.ictequipment'),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='issued_by',
            field=models.ForeignKey(help_text='ICT Officer who issued the device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_equipment', to=settings.AUTH_USER_MODEL),
        ),
    ]
