# Generated by Django 5.0.8 on 2025-09-22 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="actual_hours",
        ),
        migrations.RemoveField(
            model_name="task",
            name="estimated_hours",
        ),
        migrations.AddField(
            model_name="task",
            name="actual_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
    ]
